kind: Pod
apiVersion: v1
metadata:
  name: storage-pod
spec:
  containers:
    - name: my-frontend
      image: busybox
      command:
        - sleep
        - "36000"
      volumeMounts:
      - mountPath: "/data"
        name: my-do-volume
  volumes:
    - name: my-do-volume
      persistentVolumeClaim:
        claimName: kplabs-pvc