# kubernetes role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: a
  name: pod-reader
rules:
- apiGroups: ["", extentions", "apps"]
  resources: ["pods", "deployments", "replicasets"]
  verbs: ["get", "watch", "list"]

---
# kubernetes role binding
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding
metadata:
  name: read-pods
  namespace: a
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: kube
  apiGroup: rbac.authorization.k8s.io