apiVersion: v1
kind: Pod
metadata:
  name: limit-pod1
spec:
  containers:
  - name: limit-container
    image: nginx
    resources: #for the scheduling requests will be primary consern not limits
      requests:
        memory: "20Mi"
        cpu: "0.2"
      limits:
        memory: "500Mi"
        cpu: "0.5"
