apiVersion: v1
kind: Pod
metadata:
  name: limit-pod
spec:
  containers:
  - name: limit-container
    image: nginx
    resources: #for the scheduling requests will be primary consern not limits
      requests:
        memory: "64Mi"
        cpu: "0.2"
      limits:
        memory: "128Mi"
        cpu: "0.4"
