apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: release 
        operator: In 
        values:
          - stable
          - canary
          - blue
          - green
      
  template:
    metadata:
      labels:
        release: canary
    spec:
      containers:
      - name: nginx
        image: nginx