apiVersion: v1
kind: Pod
metadata:
  name: secretmount1
spec:
  containers:
  - name: secretmount1
    image: nginx
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: firstsecret
            key: dbpass
  restartPolicy: Never